package traffic;

public enum EventType {
    SESSION_START,
    CONNECT_CONTROLLER,
    SET_AUTOMOBILE_ROUTE_STATE,
    SET_CYCLIST_ROUTE_STATE,
    SET_PEDESTRIAN_ROUTE_STATE,
    SET_BOAT_ROUTE_STATE,
    ENTITY_ENTERED_ZONE,
    ENTITY_EXITED_ZONE,
    SET_BRIDGE_WARNING_LIGHT_STATE,
    REQUEST_BRIDGE_STATE,
    REQUEST_BARRIERS_STATE,
    REQUEST_BRIDGE_ROAD_EMPTY,
    REQUEST_BRIDGE_WATER_EMPTY,
    ACKNOWLEDGE_BRIDGE_STATE,
    ACKNOWLEDGE_BARRIERS_STATE,
    ACKNOWLEDGE_BRIDGE_ROAD_EMPTY,
    ACKNOWLEDGE_BRIDGE_WATER_EMPTY
}
