package traffic;

public enum EventType {
    SESSION_START,
    CONNECT_CONTROLLER,
    SET_AUTOMOBILE_ROUTE_STATE,
    SET_CYCLIST_ROUTE_STATE,
    SET_PEDESTRIAN_ROUTE_STATE,
    SET_BOAT_ROUTE_STATE,
    ENTITY_ENTERED_ZONE
}
